### ISSUE TITLE
React-native support

### ISSUE THREAD

**Issue by ciaoamigoschat** [livekit/livekit-react#10]
Hi, are you planning to develop the SDK for react-native?

**Comment by davidzhao** [comment]
we do plan to support react-native in the future.

**Comment by ciaoamigoschat** [comment]
Great.. :)

**Comment by rikur** [comment]
Need this, subscribing.

**Comment by AvidDesigner** [comment]
Are you still in development? If so, how much longer to launch it for RN. We are launching our product soon, and would be a great help

**Comment by aredcomet** [comment]
Any update on this? subscribing

**Comment by davidzhao** [comment]
We have react native support planned for March-April. Just a bit more time folks.

**Comment by davidzhao** [comment]
Hey all, our react native support is here! (it's currently in beta). Check it out [here](https://github.com/livekit/client-sdk-react-native/) and let us know how it's working out for you!
