### ISSUE TITLE
How can i update display name of participant, not identity?

### ISSUE THREAD

**Issue by duiniuluantanqin** [livekit/livekit-react#103]
i try use `localParticipant.updateInfo` to change display  name of participant, but failed.
```
  let info = createBaseParticipantInfo();
  info.name = "123";
  room.localParticipant.updateInfo(info);
```

**Comment by lukasIO** [comment]
hi! 
`updateInfo` is an internal API that doesn't send updates to other participants. 
The `name` property is encoded in the token used to join a room, so you could either set it right there on the start or use one of the server SDKs to update the participant e.g. https://github.com/livekit/server-sdk-js/blob/main/src/RoomServiceClient.ts#L217
However it seems that the `updateParticipant` function doesn't yet implement the name field, so this would have to be added prior. 
As a workaround until then you could use the participant metadata to store the display name.

**Comment by duiniuluantanqin** [comment]
got it. thank you very much.
by the way, do we have any plans to add this feature, that `updateInfo` to other participants

**Comment by duiniuluantanqin** [comment]
> hi! `updateInfo` is an internal API that doesn't send updates to other participants. The `name` property is encoded in the token used to join a room, so you could either set it right there on the start or use one of the server SDKs to update the participant e.g. https://github.com/livekit/server-sdk-js/blob/main/src/RoomServiceClient.ts#L217 However it seems that the `updateParticipant` function doesn't yet implement the name field, so this would have to be added prior. As a workaround until then you could use the participant metadata to store the display name.

Sorry for bothering you again, i notice that `metadata` doesn't send updates to other participants. is it not be implemented yet?

**Comment by lukasIO** [comment]
How are you updating the metadata? The general workflow that is supported by LiveKit is to update the metadata with the server-sdks only!

**Comment by duiniuluantanqin** [comment]
> 
I'm sorry I was wrong. I use `client-sdk-js` all the time. I'll try server-sdk right now. thank you again.
