### ISSUE TITLE
Change Video Camera Resolution

### ISSUE THREAD

**Issue by Mihai-github** [livekit/livekit-react#107]
Hello guys, from my previous experiences with Webrtc what I saw, and also did for my personal project, changing the camera resolution during a video call was replacing the **old track** with the **new track created**. 

But ... my question now is how do we achieve this or maybe there is another way or ways of doing this with livekit support?

**Comment by lukasIO** [comment]
Hi! 
for this you can use the `restartTrack` API (https://docs.livekit.io/client-sdk-js/classes/LocalVideoTrack.html#restartTrack) and pass in your updated capture options!

**Comment by Mihai-github** [comment]
@lukasIO Ok, thank you ... will test this today and let you know if it works  👍.

**Comment by Mihai-github** [comment]
Hi @lukasIO, can you maybe provide a code example or something I cannot find what I have to chain in order to get access to the LocalTrack or what I have to do so I can have access to the `restartTrack` method...

Thank you!

**Comment by Mihai-github** [comment]
@lukasIO I think it should be like this:

`room.localParticipant.getTrack(Track.Source.Camera).videoTrack.restartTrack({resolution: myNewResolution})`
the key difference is you should also use the videoTrack so you can restart it, right?
For me, this is working I mean I can see the camera restarting and the resolution changing, but:

There might be a "bug" here ... maybe you can help me with this:

I see there "might be" a "bug" regarding the restartTrack method not updating the LocalVideoTrack dimensions
Why do I say this? Because after successfully restarting the video track I tried 2 different approaches to see the current dimensions of the LocalVideoTrack and using the cemeraPublication.dimensions` gave me the old dimensions and also using `roomCall?.localParticipant?.getTrack(Track.Source.Camera)?.videoTrack?.dimensions` the same thing but logging out this `cameraPublication?.track?.constraints` gives me the correct updated constrain but the thing is `.constains` is not part of the abstract class Track (`export abstract class Track extends (EventEmitter as new () => TypedEventEmitter<TrackEventCallbacks>) {}`)
But somehow it gets populated...

Maybe @lukasIO you can take a look or idk ... just asking :). 

Also are you aware of a method like the one on `GoogleMeet`  to change the `received resolution`?

**Comment by lukasIO** [comment]
to change the received resolution LiveKit has `adaptiveStream` built in, which will match the resolution automatically to the size of the video element, if you use the recommended `attach` workflow. https://docs.livekit.io/guides/room/receive/#adaptive-stream

In case you don't want to use adaptive stream, you can set the received quality manually with `publication.setVideoQuality` https://docs.livekit.io/guides/room/receive/#simulcast-controls

**Comment by Mihai-github** [comment]
@lukasIO For what the project wants to achieve is to allow any user to set the resolution received from other users ... Like the Google Meet platform with the option called `Receive resolution (maximum)`.
![image](https://user-images.githubusercontent.com/56633911/196519595-a585e90b-61cf-4b6a-a73b-689c7e496ee7.png)

So seems like the way to go is to use `publication.setVideoQuality` event though does not support setting actual resolutions like 360, 720, etc...

`export enum VideoQuality {
  LOW = 0,
  MEDIUM = 1,
  HIGH = 2,
  OFF = 3,
  UNRECOGNIZED = -1,
}`

**Comment by davidzhao** [comment]
you'd need to disable adaptiveStream and call [setVideoDimensions](https://docs.livekit.io/client-sdk-js/classes/RemoteTrackPublication.html#setVideoDimensions)

**Comment by Mihai-github** [comment]
Ok, thank you, guys. Will try this today later in the day and let you know,

Thank you again 👍

**Comment by Mihai-github** [comment]
@lukasIO @davidzhao I cannot find how can I can get access to the following types ... 

```
track: RemoteTrack,
publication: RemoteTrackPublication,
participant?: RemoteParticipant,
```
I've checked the docs as @lukasIO suggested (https://docs.livekit.io/guides/room/receive/#simulcast-controls) but what types the function accepts I can not get hold of them :(

Maybe you guys can help me, please :)

Thank you very much guys 👍

**Comment by Mihai-github** [comment]
Oh, I see so the function is supposed to work with the `trackSubscribed` event fired when someone else joins the room and turns on the video camera, got it ... makes sense now.

**Comment by davidzhao** [comment]
@Mihai-github please refer to our docs and example apps (in this repo).
