### ISSUE TITLE
RemoteTrackPublication - setEnabled(false) freezes the camera on last frame received but not removing it from appearing

### ISSUE THREAD

**Issue by Mihai-github** [livekit/livekit-react#108]
Hi,

   What I'm trying to achieve is for a RemoteTrackPublication to remove the server from sending the video stream but also turn off the camera.
  Following the docs, I've come across a method called `setEnabled` which is supposed to do this but what my project would also need is also turning off the cameras not just freezing them on the last frame received from the server. 
  The method can be found for others here -> `https://docs.livekit.io/client-sdk-js/classes/RemoteTrackPublication.html#setEnabled`

**Comment by lukasIO** [comment]
you would want to call `mute()` on the publication for that!

**Comment by lukasIO** [comment]
ah, sorry. misread the question, reopening. for remote track publications. reopening

**Comment by Mihai-github** [comment]
@lukasIO No problem, maybe you know a way of achieving this or the only way now is just controlling the rendering of the participants ?

**Comment by davidzhao** [comment]
had a discussion in Slack with Mihai. The issue was that the current React component does not render the backup widget when the track had been manually disabled by the user. This is an acceptable behavior; and we are also happy to accept an PR that makes it aware of enable/disabled state.
