### ISSUE TITLE
Participant not disconnected from the Room when pressing the browser back button

### ISSUE THREAD

**Issue by Mihai-github** [livekit/livekit-react#111]
Hi,

    I'm having some issues with LocalParticipant on pressing the browser back button still being connected to the room even though the docs say:
--------------------------------------------------------------------------------------------------------------
NOTE:

On some platforms (JavaScript and Swift), Room. disconnect is called automatically when the application exits
--------------------------------------------------------------------------------------------------------------

Even if I'm trying using useEffect unmount method to try to disconnect myself from the room I can see in the logs I'm connected to that room still.

The interesting thing is by pressing the LIvekit default end call button and doing this:

<LiveKitRoom
   onLeave(async () => {
        await roomCall?.disconnect();
        history.push('/somewhere')
   })
/>

I'm disconnected from the rooms so everything is ok, so there might be an issue here @lukasIO @davidzhao  what do you think?

**Comment by lukasIO** [comment]
discussed this further with @Mihai-github on slack, he said it's reproducable on example.livekit.io
> the “bug” with disconnecting and reconnecting to the room I reproduced it also with the example you guys are hosting over here
