### ISSUE TITLE
Missing RemoteTrack functionality

### ISSUE THREAD

**Issue by helderjbe** [livekit/livekit-react#115]
I want to add a subscriber-side mute (muting a remote participant only for a specific user) using the available functionality in _livekit-react_.

According to the docs ([https://docs.livekit.io/client/receive/#enabling/disabling-tracks](https://docs.livekit.io/client/receive/#enabling/disabling-tracks)), this is not possible in _livekit-react_ as remote publications do not implement `publication.setEnabled()`

How can I make this work using livekit-react?

**Comment by lukasIO** [comment]
hi! 
you could do this by calling `participant.setVolume(0)` which will mute the remote participant locally (only for the local user). Does that help?

**Comment by helderjbe** [comment]
I tried doing the following:

Method 1:
```
const room = useRoom(...)
room.participants.forEach(participant => partcipant.setVolume(0)) // Not implemented
```

Method 2:
```
const room = useRoom(...)
(...)
const participant = useParticipant(...)
participant.setVolume(0) // Not implemented
```

Afaik these are the only 2 ways of exposing the methods of participants in a React way (without dealing with event listeners myself)

Is there some other way I should be doing this?

**Comment by lukasIO** [comment]
what version of `livekit-client` do you have installed?

**Comment by helderjbe** [comment]
> what version of `livekit-client` do you have installed?

    "@livekit/react-components": "^1.1.0",
    "@livekit/react-core": "^1.1.0",
    "livekit-client": "^1.6.0",

**Comment by lukasIO** [comment]
Make sure to only perform `setVolume` on `RemoteParticipants`, it's only implemented for that class. 
https://docs.livekit.io/client-sdk-js/classes/RemoteParticipant.html#setVolume
