### ISSUE TITLE
<LiveKitRoom />  controlRenderer and participantRender mounts and un-mounts on re-renders

### ISSUE THREAD

**Issue by Mihai-github** [livekit/livekit-react#118]
Hi, @lukasIO

   I've tried to create a basic example showcasing the issue, but in a nutshell when the `<Room />` component re-renders because of the `<button />` calling `setTestState()` (normal behavior having a re-render), but when in my example let's say I wanna render the controllers with a different design (same for participantRender) the component as a consequence of the `PARENT COMPONENT (<Room />)` re-render the `<Controller />` is `un-mounting` and `mounting` back and this should not happen, right?

Note: This can be seen easily having images rendered that are not hosted locally so they are taken from some source so when the `un-mounting and mounting` behavior happens you can see this and also inspecting the `Network Tab` is visible they are re-downloaded.

```
export const Controller = () => {
    useEffect(() => {
        console.log('mount')
        return () => console.log("un-mount");
    }, [])

   return (<img src={someSource} alt="image" />)
}

export const Room = () => {
    const [testState, setTestState] = useState<boolean>(false);
    const [token, setToken] = useState<string>('');
    
   useEffect(() => {
        (async () => {
                try{
                      const {data} = await geRoomToken();
                      if(data && data.token) return setToken(data.token)
                      alert('No token')
                }catch(err) {alert(err)}
        })()
   }, [])

    return (
      <>
        <button onClick={() => setTestState(prev => !prev)}>TEST</button>
        <LiveKitRoom
          url={process.env.REACT_APP_LIVEKIT_WS_URL as string}
          token={token}
          controlRenderer={() => <Controller />}
        />
      </>
    );
}
```

Hope the example :)

**Comment by lukasIO** [comment]
hi @Mihai-github 
thanks for the report. This unfortunately a short-coming of how this library is architected. 

As soon as the `room` state changes the whole LiveKit room will be re-rendered. 
FWIW the new components at https://github.com/livekit/components-js do not suffer from that issue. 

Will close as we're currently not planning to change that behaviour.

**Comment by Mihai-github** [comment]
Hi @lukasIO,

   I see, but I have one question why is this short-coming related to the `room state changes`. If I log the `room.state`, I can see it does not change from `connected` to something else ... so I don't know how these 2 are related maybe you can explain a bit more this?

**Comment by lukasIO** [comment]
sorry, misunderstood the question! 

that can be easily fixed by changing the controlRenderer prop in your code from 
```
controlRenderer={() => <Controller />}
```
to 
```
controlRenderer={Controller}
```

**Comment by Mihai-github** [comment]
Have checked and works like this for some kind of the reason I don't understand (maybe you can explain, please :)) ) but what I do if let's say I return like this
`controlRenderer={() => <Controller />}`
Why I'm asking because I need to also be able to pass props In my actual use case with the application I develop
`controlRenderer={() => <Controller prop1={prop1}  prop2={prop2} ...etc />}`

**Comment by Mihai-github** [comment]
Oh, damn I understand why. I did not think at all of this was the issue. 

I also tested this with my custom code for the participantRender and the issue with the `mounting and unmounting` seems to be solved.

Thank you @lukasIO
