### ISSUE TITLE
Need help with building a Custom UI

### ISSUE THREAD

**Issue by yashrajpahwa** [livekit/livekit-react#12]
HI, 

I am facing some issues with building a custom UI in NextJS 12. It would be great if someone could help me with it.
I want to be able to use the hooks provided by the library for the connection and other underlying logic.

Thanks

**Comment by davidzhao** [comment]
please join our [Slack community](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg) where folks can help.
