### ISSUE TITLE
Leaving the call

### ISSUE THREAD

**Issue by Mihai-github** [livekit/livekit-react#126]
Hey, 
    
     I am having an issue when changing the route by calling history.push(). For some kind reason, which at the moment I could not figure out yet when calling the history.push method I get the following error

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
LiveKitRoom@http://localhost:3011/static/js/2.chunk.js:17290:13`

Witch seems like is coming from the LivekitRoom component from the **StackTrack** (image attached below)

![image](https://user-images.githubusercontent.com/56633911/223805361-c715c91b-6cce-4e22-9d87-d72d868d4c4b.png)

 
Not sure if is something wrong with what I do or if it's just maybe an internal issue with the library.

Maybe is related to this clean up done on the unmount of the component

`useEffect(() => {
    if (roomState.room) {
      roomState.connect(url, token, connectOptions).then((room) => {
        if (!room) {
          return;
        }
        if (onConnected && room.state === ConnectionState.Connected) {
          onConnected(room);
        }
      });
    }
    return () => {
      if (roomState.room?.state !== ConnectionState.Disconnected) {
        roomState.room?.disconnect();
      }
    };
  }, [roomState.room]);
`

**Comment by lukasIO** [comment]
this is most likely because `room.disconnect()` is async and by calling `history.push` the component might be unmounting already even though `disconnect()` hasn't completed. 
A workaround could be to make sure in your app that you call `await room.disconnect()` before changing the route! 
(also check out the new components (https://github.com/livekit/components-js), as we will deprecate this packages soon)

**Comment by Mihai-github** [comment]
@lukasIO Exactly this seems to be the cause, after some more debugging I realized this is the issue and started adding exactly what you said, disconnecting from the room before redirecting.

I was going to post today for others if they might come across this, but you were faster than me 👍
