### ISSUE TITLE
Is it possible to change the number of simulcast layers?

### ISSUE THREAD

**Issue by Yun-David-Youngjoon** [livekit/livekit-react#128]
Currently, three simulcast layers are being sent.

Can't I send only two types?

For example, only 480p and 720p.

**Comment by Yun-David-Youngjoon** [comment]
There seems to be a problem with the `videoSimulcastLayers` option......

From h540, even if two types of layers are inserted, three layer types are being responded.

![스크린샷 2023-03-10 오후 2 36 39](https://user-images.githubusercontent.com/90605249/224232562-488c64d9-5067-4713-841e-553056b9fb6d.png)

**Comment by davidzhao** [comment]
to publish two layers, only specify a single layer in there. the original source will be published as well.
