### ISSUE TITLE
MS Surface Pro 2:  Stuck on “Rear Camera”

### ISSUE THREAD

**Issue by maronewyork** [livekit/livekit-react#13]
Microsoft Surface Pro 2
Windows 10 Pro
Chrome Version 95.0.4638.69

Livekit video call defaults to/gets stuck on the “rear camera” -

![C0BC7B3E-7942-4629-85FA-89C9396548F0](https://user-images.githubusercontent.com/37821339/140256666-da3e4b92-b566-4267-8bcc-376256d89680.jpeg)

when user tries to change to Front LifeCam toggle does not work

NOTE: this does not happen on Skype nor Zoom on same Device/OS/Connection

**Comment by davidzhao** [comment]
closing as this is several months old
