### ISSUE TITLE
Steps to deploy in a machine as locally?

### ISSUE THREAD

**Issue by GRNHACKER** [livekit/livekit-react#31]
??

**Comment by lukasIO** [comment]
hi, 
if you are asking about how to run livekit-server locally, here are the docs for that: https://docs.livekit.io/guides/getting-started#starting-with-docker

for general questions, the livekit community on slack is active [here](https://join.slack.com/t/livekit-users/shared_invite/zt-rrdy5abr-5pZ1wW8pXEkiQxBzFiXPUg)

**Comment by GRNHACKER** [comment]
> 
https://example.livekit.io/#/ 
i want to deploy this demo site on my local machine

**Comment by lukasIO** [comment]
the code for it is in the example folder: https://github.com/livekit/livekit-react/tree/master/example

**Comment by GRNHACKER** [comment]
> the code for it is in the example folder: https://github.com/livekit/livekit-react/tree/master/example

facing error:-

`Failed to compile.

../dist/index.modern.js 358:88
Module parse failed: Unexpected token (358:88)
File was processed with these loaders:
 * ../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
|   if (enableVideo) {
>     const enabled = !((camPub === null || camPub === void 0 ? void 0 : camPub.isMuted) ?? true);
|     videoButton = React__default.createElement(VideoSelectButton, {
|       isEnabled: enabled,
`

**Comment by GRNHACKER** [comment]
> the code for it is in the example folder: https://github.com/livekit/livekit-react/tree/master/example

Thanks.....working fine now

**Comment by GRNHACKER** [comment]
> the code for it is in the example folder: https://github.com/livekit/livekit-react/tree/master/example

hey, where can i change the name, uid which is set default like tony_stark, stark_tower. ??

**Comment by davidzhao** [comment]
https://docs.livekit.io/guides/access-tokens
