### ISSUE TITLE
Device chooser is sometimes empty due to timing issue

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-react#38]
Sometimes the device switcher shows up without any devices. This could be a timing issue / state synchronization. Potentially caused by the permission approval process.

<img width="326" alt="image (4)" src="https://user-images.githubusercontent.com/320582/160541671-1abb5114-48f9-40db-8d6e-34c14173cc07.png">

**Comment by lukasIO** [comment]
I'm wondering what the best way to handle this consistently would be. 

The reason why it shows up empty is that the call to `enumerateDevices` returns an empty array if `getUserMedia` hasn't been requested before.

We could solve this either on the button level and do something like 
```ts
    const devices = await Room.getLocalDevices("videoinput");
    if (devices.length === 0) {
      await navigator.mediaDevices.getUserMedia({ video: true });
    }
    setSources(devices);
```
which has the advantage that it works in a "standalone" way. The downside is that the permissions dialog is popping up as soon as the button renders (given that the permissions haven't been granted beforehand already).

Alternatively we could be passing a prop down to the button that fires `listDevices` once getUserMedia has been resolved.

To keep in mind however: If we only ask for get video devices, we still won't be able to list audio devices. We would have to ask for both (at the same time or after one another).

**Comment by davidzhao** [comment]
I wonder if we could handle this within `Room.getLocalDevices`? there we know exactly which kind of device they are asking for, and could request getUserMedia if both of the following are true:
* list returns empty
* we have not yet asked for getUserMedia

wdyt?

**Comment by lukasIO** [comment]
seems like a good solution, the only thing I'm not entirely happy with is that if people want a single permissions popup for both audio and video, Room.getLocalDevices would currently not allow that.

**Comment by davidzhao** [comment]
what about making the `kind` arg optional? so that if you called it without a filter, it'll ask for both permissions and return an unfiltered list of devices.

**Comment by lukasIO** [comment]
I like that!
