### ISSUE TITLE
react 18.0.0 support

### ISSUE THREAD

**Issue by prp-e** [livekit/livekit-react#40]
Greetings. 
Please consider the newest release of react `18.0.0`. This library can not be installed on a `18.0.0` project.

**Comment by anupriya17** [comment]
We're using with react 18 for a while from react 18-rc and working fine

**Comment by scott-lc** [comment]
Tangentially related to this, `livekit-react` has a hard dependency on `"livekit-client": "^0.17.1"`, which makes it incompatible with the latest release of `livekit/client-sdk-js` (`v0.18.0`).
