### ISSUE TITLE
Must use import to load ES Module in Nextjs

### ISSUE THREAD

**Issue by Dolir** [livekit/livekit-react#43]
I'm trying to use livekit-react in nextjs and throws me this error:

Server Error
```
Error: Must use import to load ES Module: C:\projectFolder\node_modules\livekit-client\dist\livekit-client.umd.js
require() of ES modules is not supported.
require() of C:\projectFolder\node_modules\livekit-client\dist\livekit-client.umd.js from C:\projectFolder\node_modules\livekit-react\dist\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename livekit-client.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\projectFolder\node_modules\livekit-client\package.json.
```

And when i removed "type": "module" in the package.json of livekit-client, it was able to run

"livekit-client": "^0.18.3",
"livekit-react": "^0.7.1",
"next": "^12.1.5",

# To reproduce: 

1. Create next app
2. Use basic template of livekit-react for connecting to a room
3. Go to the page and see error

**Comment by lukasIO** [comment]
hi @Dolir, 
thanks for the report. we are currently ironing out the last bits to make the client sdk work across all frameworks. the next livekit-client update will have a fix for it.

**Comment by lukasIO** [comment]
@Dolir could you try with version `0.18.4-RC5` and see if it fixes your issues?

**Comment by Dolir** [comment]
Yes, now it works
