### ISSUE TITLE
Maximum update depth exceeded in GridStage useffect hook

### ISSUE THREAD

**Issue by anupriya17** [livekit/livekit-react#56]
This is not visible due to the hook is missing dependencies but if we add those dependencies we'll run into infinite loop warning due to setVisibleParticipants.

```
Maximum update depth exceeded. 
This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

https://github.com/livekit/livekit-react/blob/2857065a4d058bff0238513db37a6f80683a41f1/packages/components/src/components/desktop/GridStage.tsx#L81

I think there should be some check to avoid rerender loop in the useffect hook something like this:

```
    if(visibleParticipants.length !== newParticipants.length) {
      setVisibleParticipants(newParticipants);
    }
```

The warning can be reproduced by changing this
https://github.com/livekit/livekit-react/blob/2857065a4d058bff0238513db37a6f80683a41f1/packages/components/src/components/desktop/GridStage.tsx#L82
```
  }, [participants, visibleParticipants, room?.activeSpeakers, room?.localParticipant, room?.participants]);
```

**Comment by anupriya17** [comment]
Hi @lukasIO 

Thanks for quick response. I'm newbie to hooks and i see warning if the ```visibleParticipants``` not added to dependency array like.
```
React Hook useEffect has a missing dependency: 'visibleParticipants'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

I can disable the warning by ```// eslint-disable-next-line  react-hooks/exhaustive-deps ``` but which is against the react team recommendations.  May be I'm wrong.  Feel free to close the issue. Thanks

**Comment by davidzhao** [comment]
@anupriya17 it's fine to ignore that warning. in this case we are reading the last state of visibleParticipants, but don't want to recompute when it changes.
