### ISSUE TITLE
Unabled to track isSpeaking 

### ISSUE THREAD

**Issue by suryakumara** [livekit/livekit-react#66]
Hi, I have question. Why I am unable to track speaking for Remote Participant ? I did the same with all participants. Eg. from stageRendere, I loop all participant from `roomState` and finally use useParticipant to get `isSpeaking` state for each. However I only local Participant to change.

**Comment by davidzhao** [comment]
Can you post a code snippet showing how you are using it?

`useParticipant` will trigger updates when speaking status has changed.
