### ISSUE TITLE
Leave the room on unmounted

### ISSUE THREAD

**Issue by rifaldhiaw** [livekit/livekit-react#68]
HI, thanks for the awesome library. Little question here, shouldn't it be better if it automatically leave / disconnect from the room if the component unmounted ?

**Comment by lukasIO** [comment]
hi @rifaldhiaw, 
Which component do you mean? `LiveKitRoom`?

**Comment by rifaldhiaw** [comment]
Ah sorry about the missing detail, I was looking at LiveKit React Component Library when I fill the issue. Yup, it's the `LiveKitRoom` one.

I was trying to use the built-in UI, expecting that if it is mounted it will be auto rejoin and also if it is unmount it will be auto leave. But, turns out it does not simply leave after unmounted (?). 

But, anyway it's just my opinion, and at the end I use the Livekit React Core one. So feel free to close the issue. Thanks for the reply btw

**Comment by lukasIO** [comment]
This is implemented now 🎉
