### ISSUE TITLE
useRoom hook cleanup

### ISSUE THREAD

**Issue by Snowblaze** [livekit/livekit-react#71]
Hey. I have the following issue: my component is always mounted and it uses useRoom hook, when I try to disconnect and then reconnect to the call, an error is thrown that there are multiple items with the same key. As far as I can tell the problem lies in the internal state of the hook, so I have modified it to clean up its state and now it works like a charm. What do you think about that? If you want to, should I make a PR?

**Comment by lukasIO** [comment]
I think this should be fixed with the latest changes, if not feel free to re-open!
