### ISSUE TITLE
would be useful to pass URL as query parameter to example.livekit.io

### ISSUE THREAD

**Issue by mwk24** [livekit/livekit-react#72]
example.livekit.io is handy for quick testing, but it would be *even* nicer to be able to bookmark a link to it which includes my LiveKit URL passed as a query param :)

**Comment by lukasIO** [comment]
that's a nice idea! would you want to submit a PR?

**Comment by mwk24** [comment]
:) yes, i could do that, but i not a react expert so it's unlikely to happen anytime soon

**Comment by lukasIO** [comment]
sure, I'll keep the issue open and if you decide to start working on it, just drop a note here and I'll know that the issue is in progress!

**Comment by bekriebel** [comment]
I wanted something like this for my own implementation based on the sample page, so I pushed a PR that adds it here as well.
