### ISSUE TITLE
Question: List live rooms?

### ISSUE THREAD

**Issue by nvsd** [livekit/livekit-react#76]
I might be missing it but is there a way to get all of the currently open rooms?

**Comment by lukasIO** [comment]
Hi @nvsd,
we do not expose any functionality to list rooms on the client side (mostly for security concerns). 
You can use the server sdks (for js: https://github.com/livekit/server-sdk-js) to list all active rooms, but obviously strongly recommend to put this functionality in a API endpoint and query that endpoint from your frontend.

**Comment by nvsd** [comment]
Sounds like a plan. Thanks for pointing me in the right direction.
