### ISSUE TITLE
Connection problem over insecure url

### ISSUE THREAD

**Issue by merazgasalim** [livekit/livekit-react#97]
Hi
I received complaints from some of my app users telling me that they are sometimes **unable** to connect and they get the following error `could not establish signal connection`

My website is secure but I noticed that it's not secure on their ends. After investigation I found that they are using old operating systems especially **Windows 7** which do not recognize my website ssl certificate

I found a tutorial about fixing this issue on Windows 7. After I sent it to them they became able to connect.

I think that the `PreJoinPage.tsx` should handle this situation in the `connectToRoom` function by adding something like this

```
  const connectToRoom = async () => {
   ....

  if (
      window.location.protocol === 'http:' &&
      !url.startsWith("ws://localhost")
    ) {
      alert('Your OS/Browser couldn't recognize our ssl certificate, Please update your OS security ');
      return;
    }
   .......
  };
```

**Comment by davidzhao** [comment]
@merazgasalim that logic doesn't seem to be right.

In any case, I'm glad to hear you found the issue. SSL certificates and their validity are outside of the scope of this project.
